name: FINAL UserBot
#ูุง ุงุญูู ุงุทูุงูุง ูุณุฎ ุงูููุฏ ุงู ุงุณุชุฎุฏุงู ุงูุทุฑููุฉ ููุนุงูุฉ ุจุฏูู ุฐูุฑ ุงููุตุฏุฑ ูุณุงููู ุฎุตููู ููู ุงูุฏูู 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: final-userbot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ุชุญููู ุงูุงุตุฏุงุฑ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ุชููุฆุฉ Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: ุฅูุดุงุก ูููุงุช ุจูุงูุงุช ุฌุฏูุฏุฉ (ุจุฏูู ุฌูุจ ุงููุฏููุฉ)
        run: |
          echo "๐ ุจุฏุก ุชุดุบูู ุฌุฏูุฏ ุจุฏูู ุฌูุจ ุงูุจูุงูุงุช ุงููุฏููุฉ"
          echo "๐ ุณูุชู ุฅูุดุงุก ูููุงุช ุฌูุณุฉ ุฌุฏูุฏุฉ ุฅุฐุง ูู ุชูู ููุฌูุฏุฉ"
          # ุฅูุดุงุก ูููุงุช ุฃุณุงุณูุฉ ุฅุฐุง ูู ุชูู ููุฌูุฏุฉ
          touch data.db 2>/dev/null || true
          touch config.json 2>/dev/null || true
          echo "โ ุฌุงูุฒ ููุชุดุบูู ุจุจูุงูุงุช ุฌุฏูุฏุฉ"

      - name: ุชุญููู ุงููุชุทูุจุงุช
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: ูุชุทูุจุงุช ุงููููุฒู
        run: |          
          sudo apt-get install -y ffmpeg
                              
      - name: ุจุฏุก ุงูุณูุฑุณ
        run: python main.py

      - name: ุญูุธ ุจูุงูุงุช ูุฐุง ุงูุชุดุบูู
        if: always()
        run: |
          git checkout main
          git checkout bot-final-storage 2>/dev/null || git checkout -b bot-final-storage
          echo "main.py" >> .gitignore
          echo "data.py" >> .gitignore
          echo "FINAL/" >> .gitignore
          git add --all
          git commit -m "๐ค Auto-update bot data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "โน๏ธ ูุง ุชูุฌุฏ ุชุบููุฑุงุช ููุญูุธ"
          git push origin bot-final-storage --force || echo "โ ูุดู ุฑูุน ุงูุจูุงูุงุช"
          git checkout main

      - name: ุชุงููุฏ ุงูุนูููุงุช
        run: |
          echo "โ ุงูุนูููุฉ ุงูุชูุช ุจูุฌุงุญ"
          echo "๐ฆ ุงูุจูุงูุงุช ูุญููุธุฉ ูู ูุฑุน: bot-final-storage"
